name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
    - run: pip install vim-vint
    - run: vint .
